version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pedrotroller/php-cs-custom-fixer
    versions:
    - 2.23.1
    - 2.24.0
  - dependency-name: symfony/filesystem
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/error-handler
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/config
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/finder
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/debug
    versions:
    - 4.4.19
