---
version: '2.1'

orbs:
    node: circleci/node@1.1

composer: &composer
    run: |
        composer global require hirak/prestissimo --no-progress
        composer install -vvv --profile --no-interaction

tests: &tests
    run: |
        vendor/bin/php-cs-fixer fix --dry-run --diff --stop-on-violation
        vendor/bin/phpspec run

jobs:

    php-7-2:
        docker:
            -   image: circleci/php:7.2
        steps:
            - checkout
            -   <<: *composer
            -   <<: *tests
    php-7-3:
        docker:
            -   image: circleci/php:7.3
        steps:
            - checkout
            -   <<: *composer
            -   <<: *tests
    php-7-4:
        docker:
            -   image: circleci/php:7.4
        steps:
            - checkout
            -   <<: *composer
            -   <<: *tests
    release-test:
        executor:
            name: node/default
        steps:
            - node/install
            - checkout
            -   node/with-cache:
                    steps:
                        -   run: npm install
            -   run: node_modules/.bin/semantic-release --dry-run

    release:
        executor:
            name: node/default
        steps:
            - node/install
            - checkout
            -   node/with-cache:
                    steps:
                        -   run: npm install
            -   run: node_modules/.bin/semantic-release

workflows:
    version: 2
    PR:
        jobs:
            - php-7-2
            - php-7-3
            - php-7-4
            - release-test
            -   release:
                    requires:
                        - php-7-2
                        - php-7-3
                        - php-7-4
                    filters:
                        branches:
                            only:
                                - master

