---
version: '2.1'

orbs:
    node: circleci/node@1.1

composer: &composer
    run: |
        composer update -vvv --profile --no-interaction
composer_with_lowest_dependencies: &composer_with_lowest_dependencies
    run: |
        composer update --prefer-lowest --prefer-stable

tests: &tests
    run: |
        vendor/bin/php-cs-fixer fix --dry-run --diff --stop-on-violation
        vendor/bin/phpspec run

jobs:

    tests:
        parameters:
            php-version:
                type: string
        docker:
            -   image: "circleci/php:<< parameters.php-version >>"
        steps:
            - checkout
            -   run: php --version
            -   <<: *composer
            -   <<: *tests
    release-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install
            -   node/with-cache:
                    steps:
                        -   run: npm install
            -   run: node_modules/.bin/semantic-release --dry-run

    tests-with-lowest-dependencies:
        parameters:
            php-version:
                type: string
        docker:
            -   image: "circleci/php:<< parameters.php-version >>"
        steps:
            - checkout
            -   <<: *composer_with_lowest_dependencies
            -   <<: *tests
    release:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install
            -   node/with-cache:
                    steps:
                        -   run: npm install
            -   run: node_modules/.bin/semantic-release
workflows:
    version: 2
    PR:
        jobs:
            -   tests:
                    matrix:
                        parameters:
                            php-version: [ "7.4", "latest" ]

            -   tests-with-lowest-dependencies:
                    matrix:
                        parameters:
                            php-version: [ "7.4", "latest" ]
            - release-test
            -   release:
                    requires:
                        - release
                        - tests
                        - tests-with-lowest-dependencies
                    filters:
                        branches:
                            only:
                                - master
