---
version: '2'

composer: &composer
  run: |
    composer global require hirak/prestissimo --no-progress
    composer install -vvv --profile --no-interaction

tests: &tests
  run: | 
    vendor/bin/phpspec run

jobs: 
  php 7.1: 
    docker: 
      - image: circleci/php:7.1
    steps: 
      - checkout
      - <<: *composer
      - <<: *tests
  php 7.2: 
    docker: 
      - image: circleci/php:7.2
    steps: 
      - checkout
      - <<: *composer
      - <<: *tests
  php 7.3: 
    docker: 
      - image: circleci/php:7.3
    steps: 
      - checkout
      - <<: *composer
      - <<: *tests
  release:
      docker: 
        - image: circleci/node:8
      steps: 
        - type: checkout 
        - run: sudo npm install -g semantic-release
        - run: semantic-release

workflows: 
  version: 2 
  PR: 
    jobs: 
      - php 7.1
      - php 7.2
      - php 7.3
      - release: 
          requires: 
            - php 7.1
            - php 7.2
            - php 7.3
          filters: 
            branches: 
              only:
                - master

